# Generated by Django 2.2.2 on 2019-06-26 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Currency')),
            ],
            options={
                'verbose_name': 'Trading - Sell',
                'verbose_name_plural': 'Trading - Sell',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.Currency')),
            ],
            options={
                'verbose_name': 'Trading - Buy',
                'verbose_name_plural': 'Trading - Buy',
            },
        ),
    ]
